### ISSUE TITLE
Ruby and/or Clojure support for languages

### ISSUE THREAD

**Issue by pvdvreede** [joergen7/cuneiform#42]
Hi there, 

Love this idea and it works quite well for any data transformation intensive tasks.

Wondering if its possible to add support for Ruby and Clojure to this? I can help with syntax (more so for Ruby than Clojure) if you need some help with the pre/post script stuff...

Thanks!

**Comment by pvdvreede** [comment]
PS I see you are porting this to Erlang? Thats pretty cool, the boot up times will certainly be better :smile:

Are you planning to maintain the Java and Erlang version in parallel, or eventually switch over to Erlang?

**Comment by joergen7** [comment]
Hey,

> Wondering if its possible to add support for Ruby and Clojure to this?

It is definitely. Ruby is an obvious candidate. But also for Clojure I'm positive it can be integrated in Cuneiform. We had CLisp support in [Cuneiform 1.0.0](https://github.com/joergen7/cuneiform-legacy).

>  I see you are porting this to Erlang

In the Erlang version it is also much simpler to integrate foreign languages. In the Java branch one has to inherit from the [de.huberlin.wbi.cuneiform.core.invoc.Invocation](https://github.com/joergen7/cuneiform/blob/master/cuneiform-core/src/main/java/de/huberlin/wbi/cuneiform/core/invoc/Invocation.java) class and implement all abstract methods for adding a foreign language. This would be around 250 LOC. In the Erlang branch foreign language support is done via [Effi](https://github.com/joergen7/effi) where one has to implement 8 short functions (so principally an 8-liner).

> Are you planning to maintain the Java and Erlang version in parallel, or eventually switch over to Erlang?

We will eventually switch to Erlang. That doesn't mean the Java version is deprecated. I'm just not adding features anymore.

**Comment by joergen7** [comment]
We are currently supporting ten foreign languages and I have to admit that is as far as I want to carry it for the time being.

If you are willing to create your own extensions for Clojure and Ruby please create a PR on the effi repository with the apropriate extensions.
