### ISSUE TITLE
Allow the specific :cf_cre "platform" behaviour to access the full gen_server state 

### ISSUE THREAD

**Issue by zampino** [joergen7/cuneiform#54]
in the easiest form :cf_cre delegates a final (catch-all) `handle_info` to the implemented behaviour: 

in a _read only_ fashion something like: 

``` erlang
-- cf_cre.erl

handle_info(request, {Mod, rest_of_state}) ->
  apply(Mod, :info, [rest_of_state]),  
  {no_reply, State}
```

we could consider also the ability to write back to the state,
with a `handle_call` but that could imply extra undesired blocking of the process... 

_use case:_ allow third party cuneiform interpreters to introspect the current state of the runtime: 
e.g. the future cache as well as the map of the computed replies.

**Comment by joergen7** [comment]
I seem to have missed that issue. Sry, I reply just now. You are right, of course. Do you need that feature?

**Comment by zampino** [comment]
maybe let's keep this issue open, I'll come with more concrete use cases at some point.

With some past commits of yours we can already access (read) the reply-map and the runtime cache.

This issue would be about a more generic way to access the runtime state
and possibly even modify it...

**Comment by joergen7** [comment]
sure, just tell me when you need it. otherwise, I'd rather keep it simple.

**Comment by joergen7** [comment]
I understand what this issue is about. However, my guess is, no one actually needs that anymore.
