### ISSUE TITLE
Error: User defined Signal 2

### ISSUE THREAD

**Issue by bearbob** [joergen7/cuneiform#59]
Occasionally the execution of my scripts fails with the following output.
This may be related to a problem with the executing machine (Triton), but I'm not sure of that.

=INFO REPORT==== 28-Jul-2016::14:40:11 ===
Base directory:    /tmp/cf-2
Number of threads: 24
Notifying logmgr ...
logmgr received an event.
Notifying logmgr ...
Notifying logmgr ...
Notifying logmgr ...
Notifying logmgr ...
Notifying logmgr ...
Notifying logmgr ...
Notifying logmgr ...
Notifying logmgr ...
Sending {started,1,"fastqc"} to http://192.168.24.74:8080
Notifying logmgr ...
{"init ter
inating in do_boot",{eagain,[{erlang,open_port,[{spawn,"bash"},[exit_status,stderr_to_stdout,binary,{cd,"/tmp/cf-2/work/10"},{line,1024}]],[]},{effi_interact,create_port,3,[{file,"/home/bjoern/software/cuneiform-dev/_build/default/lib/effi/src/effi_interact.erl"},{line,80}]},{effi,create_port,4,[{file,"/home/bjoern/software/cuneiform-dev/_build/default/lib/effi/src/effi.erl"},{line,412}]},{effi,run,4,[{file,"/home/bjoern/software/cuneiform-dev/_build/default/lib/effi/src/effi.erl"},{line,361}]},{effi,check_run,5,[{file,"/home/bjoern/software/cuneiform-dev/_build/default/lib/effi/src/effi.erl"},{line,135}]},{local,stage,6,[{file,"/home/bjoern/software/cuneiform-dev/_build/default/lib/cuneiform/src/local.erl"},{line,151}]},{gen_queue,stage_reply,2,[{file,"/home/bjoern/software/cuneiform-dev/_build/default/lib/cuneiform/src/gen_queue.erl"},{line,100}]}]}}
/home/bjoern/bin/cuneiform: line 2: 33223 User defined signal 2   /home/bjoern/software/cuneiform-dev/_build/default/bin/cuneiform $*
        [{file,"/home/bjoern/software/cuneiform-dev/_build/default/lib/cuneiform/src/local.erl"},
                 {line,151}]},
         {gen_queue,stage_reply,2,
                    [{file,"/home/bjoern/software/cuneiform-dev/_build/default/lib/cuneiform/src/gen_queue.erl"},
                     {line,100}]}]}

**Comment by joergen7** [comment]
eagain ... never had that.

**Comment by joergen7** [comment]
eagain
        No more available OS processes.

Ask your admin!

**Comment by joergen7** [comment]
Btw, I'm working on a way to overcome partial failure in the workers. A worker smoking away with `eagain` would be just one more of these cases.

So, even if we can't get around the process limit of the OS, we can still make the workflow system continue to run. But this will be a feature of the 2.4.x branch (so way in the future).
