### ISSUE TITLE
Rename: [Error: Enoent]

### ISSUE THREAD

**Issue by bearbob** [joergen7/cuneiform#60]
If cuneiform is called for a script that does not exists, the error message looks like this:

cuneiform  doesnt.exist.cf
added IP ****\* to logmgr.

=INFO REPORT==== 4-Aug-2016::12:48:59 ===
Base directory:    /tmp/cf-**
Number of threads: 24
Error: enoent

It took me a while to notice the typo in the file name, a better error message might be something like "The called Cuneiform script "xxx" does not exist."

**Comment by joergen7** [comment]
enoent means file doesn't exist. could be clearer, you're right.

**Comment by joergen7** [comment]
now
    load error: {"doesntexist.cfl",enoent}

**Comment by joergen7** [comment]
I have changed the error message so that no hint to Erlang data structures remains.
