### ISSUE TITLE
Make: Compile-Error in rebar_core

### ISSUE THREAD

**Issue by bearbob** [joergen7/cuneiform#61]
I'm trying to install the latest cuneiform-version from the dev-branch (bff1485) and stumble upon the following compile error. I used rebar3 stable release version 3.2.0

make DEBUG=1
rebar3 escriptize
===> Expanded command sequence to be run: [{default,app_discovery},
                                                  {default,install_deps},
                                                  {default,lock},
                                                  {default,compile},
                                                  {default,escriptize}]
===> Verifying dependencies...
===> sh info:
        cwd: "/root/software/cuneiform"
        cmd: git rev-parse -q HEAD

===>   opts: [{cd,"/root/software/cuneiform/_build/default/lib/effi"}]

===> Port Cmd: git rev-parse -q HEAD
Port Opts: [{cd,"/root/software/cuneiform/_build/default/lib/effi"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof]

===> Comparing git ref 539b60f204d70163f22f27e381410687f437fb24 with 539b60f204d70163f22f27e381410687f437fb24
===> sh info:
        cwd: "/root/software/cuneiform"
        cmd: git rev-parse -q HEAD

===>   opts: [{cd,"/root/software/cuneiform/_build/default/lib/getopt"}]

===> Port Cmd: git rev-parse -q HEAD
Port Opts: [{cd,"/root/software/cuneiform/_build/default/lib/getopt"},
            exit_status,
            {line,16384},
            use_stdio,stderr_to_stdout,hide,eof]

===> Comparing git ref 68fe326f2c7585eb32a5b136dffc75428a53fc02 with 68fe326f2c7585eb32a5b136dffc75428a53fc02
===> sh info:
        cwd: "/root/software/cuneiform"
        cmd: git --git-dir="/root/software/cuneiform/_build/default/lib/getopt/.git" rev-parse --verify HEAD

===>   opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /root/software/cuneiform/_build/default/lib/getopt"}]

===> Port Cmd: git --git-dir="/root/software/cuneiform/_build/default/lib/getopt/.git" rev-parse --verify HEAD
Port Opts: [exit_status,{line,16384},use_stdio,stderr_to_stdout,hide,eof]

===> sh info:
        cwd: "/root/software/cuneiform"
        cmd: git --git-dir="/root/software/cuneiform/_build/default/lib/effi/.git" rev-parse --verify HEAD

===>   opts: [{use_stdout,false},
                       {debug_abort_on_error,
                           "Locking of git dependency failed in /root/software/cuneiform/_build/default/lib/effi"}]

===> Port Cmd: git --git-dir="/root/software/cuneiform/_build/default/lib/effi/.git" rev-parse --verify HEAD
Port Opts: [exit_status,{line,16384},use_stdio,stderr_to_stdout,hide,eof]

===> run_hooks("/root/software/cuneiform", pre_hooks, compile) -> no hooks defined

===> Compiling cuneiform
===> run_hooks("/root/software/cuneiform", pre_hooks, compile) -> no hooks defined

===> run_hooks("/root/software/cuneiform", pre_hooks, erlc_compile) -> no hooks defined

===> Uncaught error in rebar_core. Run with DEBUG=1 to see stacktrace or consult rebar3.crashdump
===> Uncaught error: undef
===> Stack trace to the error location: [{leex,file,
                                                 ["/root/software/cuneiform/_build/default/lib/cuneiform/src/cf_scan.xrl",
                                                  [{return,true}]],
                                                 []},
                                                {rebar_erlc_compiler,
                                                 compile_xrl_yrl,5,
                                                 [{file,
                                                   "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_erlc_compiler.erl"},
                                                  {line,590}]},
                                                {rebar_base_compiler,
                                                 compile_each,3,
                                                 [{file,
                                                   "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_base_compiler.erl"},
                                                  {line,134}]},
                                                {rebar_erlc_compiler,compile,
                                                 2,
                                                 [{file,
                                                   "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_erlc_compiler.erl"},
                                                  {line,104}]},
                                                {rebar_prv_compile,compile,3,
                                                 [{file,
                                                   "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_compile.erl"},
                                                  {line,122}]},
                                                {rebar_prv_compile,
                                                 '-build_apps/3-lc$^0/1-0-',3,
                                                 [{file,
                                                   "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_compile.erl"},
                                                  {line,81}]},
                                                {rebar_prv_compile,do,1,
                                                 [{file,
                                                   "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_prv_compile.erl"},
                                                  {line,54}]},
                                                {rebar_core,do,2,
                                                 [{file,
                                                   "/home/tristan/Devel/rebar3/_build/default/lib/rebar/src/rebar_core.erl"},
                                                  {line,125}]}]
===> When submitting a bug report, please include the output of `rebar3 report "your command"`
Makefile:9: recipe for target 'compile' failed
make: *** [compile] Error 1

**Comment by joergen7** [comment]
This branch is just a stub. I'm still busy modeling it. Please stick to 2.1.x versions of Cuneiform until further notice.

**Comment by bearbob** [comment]
Alright, thanks for the notice

**Comment by bearbob** [comment]
The Erlang version on my system was one update behind the current version, updating fixed the bug
