### ISSUE TITLE
list_to_existing_atom/1 breaks effi

### ISSUE THREAD

**Issue by joergen7** [joergen7/cuneiform#65]
> deftask a( b : c )in bash *{ b=$c }*
    > a( c: "h" );
    Notifying logmgr ...
    logmgr received an event.

=ERROR REPORT==== 21-Sep-2016::13:13:44 ===
Error in process <0.75.0> with exit value:
{badarg,[{erlang,list_to_existing_atom,["effi_bash"],[]},
         {effi,create_port,4,
               [{file,"/home/jorgen/git/cuneiform/_build/default/lib/effi/src/effi.erl"},
                {line,406}]},
         {effi,run,4,
               [{file,"/home/jorgen/git/cuneiform/_build/default/lib/effi/src/effi.erl"},
                {line,383}]},
         {effi,check_run,5,
               [{file,"/home/jorgen/git/cuneiform/_build/default/lib/effi/src/effi.erl"},
                {line,135}]},
         {local,stage,6,
                [{file,"/home/jorgen/git/cuneiform/_build/default/lib/cuneiform/src/local.erl"},
                 {line,151}]},
         {gen_queue,stage_reply,2,
                    [{file,"/home/jorgen/git/cuneiform/_build/default/lib/cuneiform/src/gen_queue.erl"},
                     {line,100}]}]}
{"init terminating in do_boot",{badarg,[{erlang,list_to_existing_atom,["effi_bash"],[]},{effi,create_port,4,[{file,"/home/jorgen/git/cuneiform/_build/default/lib/effi/src/effi.erl"},{line,406}]},{effi,run,4,[{file,"/home/jorgen/git/cuneiform/_build/default/lib/effi/src/effi.erl"},{line,383}]},{effi,check_run,5,[{file,"/home/jorgen/git/cuneiform/_build/default/lib/effi/src/effi.erl"},{line,135}]},{local,stage,6,[{file,"/home/jorgen/git/cuneiform/_build/default/lib/cuneiform/src/local.erl"},{line,151}]},{gen_queue,stage_reply,2,[{file,"/home/jorgen/git/cuneiform/_build/default/lib/cuneiform/src/gen_queue.erl"},{line,100}]}]}}

Crash dump is being written to: erl_crash.dump...done
init terminating in do_boot ()

**Comment by joergen7** [comment]
list_to_existing_atom/1 replaced with list_to_atom/1.

**Comment by bearbob** [comment]
The problem still exists, tried installing the current dev version ( commit fac77c7 ). After executing any task it terminates with the error above.
