### ISSUE TITLE
erl crash when using Cuneiform repl

### ISSUE THREAD

**Issue by vefjun** [joergen7/cuneiform#66]
I am on Ubuntu 16.04

Erlang/OTP 19 [erts-8.1] [source-77fb4f8] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false]

When in coneiform repl I get this error:

#{"add" => {lam,1,"add",
       {sign,[{param,{name,"c",false},false}],
             [{param,{name,"a",false},false},{param,{name,"b",false},false}]},
       {forbody,perl,"\n  $c = $a+$b;\n"}}}
> add( a: 1, b: 2 );
{"init terminating in do_boot",{undef,[{lib_refactor,get_refactoring,[[{param,{name,"a",false},false},{param,{name,"b",false},false}],#{"a"=>[{str,"1"}],"b"=>[{str,"2"}]},["/tmp/cf","-","1",47,119,111,114,107,47,49],[".",["/tmp/cf","-","1",47,114,101,112,111]],1],[]},{local,stage,6,[{file,"/media/valur/bio/cuneiform/_build/default/lib/cuneiform/src/local.erl"},{line,122}]},{gen_queue,stage_reply,2,[{file,"/media/valur/bio/cuneiform/_build/default/lib/cuneiform/src/gen_queue.erl"},{line,100}]}]}}
init terminating in do_boot ()

Crash dump is being written to: erl_crash.dump...done

**Comment by vefjun** [comment]
Works fine on dev branch:

            ___
           @@WB      Cuneiform
          @@E_____   2.2.1-snapshot 2016-10-06
     _g@@@@@WWWWWWL
   g@@#*`3@B         Type help for usage info.
  @@P    3@B
  @N____ 3@B         http://www.cuneiform-lang.org
  "W@@@WF3@B


deftask add( c : a b )in perl *{
  $c = $a+$b;
}*
> add( a: 1, b: 2 );
"3" 
>

**Comment by joergen7** [comment]
Hey vefjun,

we had this problem a week ago too on the dev branch (which is fixed now). The 2.2.0-release binary available on the [download page](http://cuneiform-lang.org/download/) works just fine. And, as you already found out, we could tackle the problem on the dev branch.

Yet, when compiling the 2.2.0-release (currently represented by the master branch) the error you described occurs, which is bad.

I suspect that the error was introduced by a [new feature]() in rebar 3.3.0 upward. The feature makes rebar3 pull in only dependencies declared in rebar.config.

We're releasing the 2.2.1 version (currently on the dev branch) in a few days. And the problem you're pointing out is another reason to do the release as early as possible.

Thanks a lot for reporting the issue.

**Comment by joergen7** [comment]
We released a version 2.2.1 of Cuneiform that compiles correctly.
