### ISSUE TITLE
Remove Profiling Parameter from CRE Function Signatures

### ISSUE THREAD

**Issue by carlwitt** [joergen7/cuneiform#74]
Profiling (and logging?) should be optional and thus moved to the Module State (ModState) data structure that is returned by the init function of Cuneiform Runtime Environments (CRE, e.g, local, htcondor). This way, not every CRE needs to cope with profiling.

**Comment by joergen7** [comment]
The CRE now hosts an HTTP server which provides access to the current state as well as a history of completed function applications.

This means that logging is fixed now. If anything must be added to the things we currently log, the cf_worker must be modified accordingly. So the way to go for custom logging now is to fork cf_worker.
