### ISSUE TITLE
rebar3 git cloning fails during compilation

### ISSUE THREAD

**Issue by fburic** [joergen7/cuneiform#85]
I'm having trouble fetching dependencies during the initial `rebar3` compilation.
The immediate cause is git not being able to clone with ssh. While I `ssh-add` my GitHub key in the current shell, `rebar3` still fails to clone (see error below). I'm not familiar with rebar3, but it could be due to the way it runs commands (i.e. spawning a shell that doesn't have the key added).

While this is something the user could fix on their end (better `ssh-agent` setup), it might be more robust and/or user friendly to use https cloning instead / as a fallback, if possible (not sure how the CI is set up etc.)
For now, I'm replacing `git://` with `https://` in the `.config` files but this is a recursive task :)

```shell
$ rebar3 escriptize 
===> Verifying dependencies...
===> Fetching cf_client (from {git,"git://github.com/joergen7/cf_client.git",
{branch,"master"}})
===> Failed to fetch and copy dep: {git,"git://github.com/joergen7/cf_client.git",
{branch,"master"}}
```

**Comment by joergen7** [comment]
thanks for pointing this issue out. should be fixed now.
